name: Build Windows EXE & Installer
on:
  workflow_dispatch:
  push:
    paths:
      - "**.py"
      - "requirements*.txt"
      - "installer.iss"
      - "assets/**"
      - ".github/workflows/build-windows.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        shell: powershell
        run: |
          Write-Host "Repo files:"; Get-ChildItem -Recurse | Select-Object FullName
          if (!(Test-Path assets\app.ico)) { Write-Error "assets\app.ico fehlt"; exit 1 }
          if (!(Test-Path installer.iss)) { Write-Error "installer.iss fehlt"; exit 1 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        shell: powershell
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements-win.txt
          pip install pyinstaller==6.6.0

      - name: Print versions (debug)
        shell: powershell
        run: |
          python -V
          python -c "import numpy, matplotlib, pandas, streamlit; print('numpy', numpy.__version__, 'matplotlib', matplotlib.__version__)"

      - name: Build EXE (PyInstaller)
        shell: powershell
        run: >
          pyinstaller --noconfirm --onefile --windowed
          --icon=assets\app.ico
          --name "ImmobilienRechner"
          launcher.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImmobilienRechner-exe
          path: dist\ImmobilienRechner.exe

      - name: Install Inno Setup (Chocolatey)
        shell: powershell
        run: choco install innosetup --yes --no-progress

      - name: Build Installer (.iss)
        shell: powershell
        run: |
          & "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" ".\installer.iss"

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImmobilienRechner-Setup
          path: dist-installer\ImmobilienRechner-Setup.exe
