name: Build Windows EXE & Installer
on:
  workflow_dispatch:
  push:
    paths:
      - "**.py"
      - "requirements*.txt"
      - "installer.iss"
      - "assets/**"
      - ".github/workflows/build-windows.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (optional) Repo-Auflistung – bricht NICHT mehr hart ab
      - name: Show repo tree (debug)
        shell: powershell
        run: |
          Write-Host "Repo files:"
          Get-ChildItem -Recurse | Select-Object FullName
          if (!(Test-Path assets\app.ico)) { Write-Warning "assets\app.ico fehlt – baue ohne Icon" }
          if (!(Test-Path installer.iss)) { Write-Error "installer.iss fehlt – bitte ins Repo legen"; exit 1 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        shell: powershell
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if (Test-Path requirements-win.txt) {
            pip install -r requirements-win.txt
          } elseif (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install streamlit pandas numpy matplotlib numpy-financial
          }
          pip install pyinstaller==6.6.0

      - name: Build EXE (PyInstaller)
        shell: powershell
        run: |
          $iconArg = (Test-Path assets\app.ico) ? '--icon=assets\app.ico' : ''
          pyinstaller --noconfirm --onefile --windowed $iconArg --name "ImmobilienRechner" launcher.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImmobilienRechner-exe
          path: dist\ImmobilienRechner.exe

      - name: Install Inno Setup (Chocolatey)
        shell: powershell
        run: choco install innosetup --yes --no-progress

      - name: Build Installer (.iss)
        shell: powershell
        run: |
          & "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" ".\installer.iss"

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImmobilienRechner-Setup
          path: dist-installer\ImmobilienRechner-Setup.exe
