name: Build Windows EXE & Installer
on:
  workflow_dispatch:        # manuell startbar
  push:
    paths:
      - "**.py"
      - "requirements*.txt"
      - "installer.iss"
      - "assets/**"
      - ".github/workflows/build-windows.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"     # stabil für Streamlit/Numpy/Matplotlib

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements-win.txt
          pip install pyinstaller

      - name: Build EXE (PyInstaller)
        run: pyinstaller --noconfirm --onefile --windowed --icon=assets\app.ico --name "ImmobilienRechner" launcher.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImmobilienRechner-exe
          path: dist\ImmobilienRechner.exe

      - name: Install Inno Setup
        run: choco install innosetup --yes --limit-output

      - name: Build Installer (.iss)
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" ".\installer.iss"'

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImmobilienRechner-Setup
          path: dist-installer\ImmobilienRechner-Setup.exe
